version: '3.8'

services:
  minecraft:
    container_name: mc-server
    hostname: plex-server
    image: itzg/minecraft-server:latest
    volumes:
      - ./.mods/cf-mods.txt:/extras/cf-mods.txt
      - /data/minecraft:/data
    environment:
      EULA: "true"
      TYPE: "CURSEFORGE"
      CF_API_KEY: "f21d7e7c-7833-4d79-a6cc-80444f5e15cb"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - "25565:25565"
      - "19132:19132/udp"
